# SLAM Toolbox parameters for delivery robot (ROS2 Humble)
slam_toolbox:
  ros__parameters:
    # Plugin params
    solver_plugin: solver_plugins::CeresSolver # predicted and observed 
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY #large maps lots of zeroes
    ceres_preconditioner: SCHUR_JACOBI # speeds
    ceres_trust_strategy: LEVENBERG_MARQUARDT #steps
    ceres_dogleg_type: TRADITIONAL_DOGLEG # step direction
    ceres_loss_function: None #error filter

    # ROS params
    odom_frame: odom #wheels
    map_frame: map #global reference
    base_frame: base_footprint #centre of the robo
    scan_topic: /scan
    use_map_saver: true
    mode: mapping  # 'mapping' or 'localization'

    # Lifecycle params auto configure and start the node
    lifcycle_startup: true

    # General params
    debug_logging: false #no extra logs 
    throttle_scans: 1 #use all scans
    transform_publish_period: 0.02 #tf
    map_update_interval: 5.0 
    resolution: 0.05
    max_laser_range: 12.0
    minimum_time_interval: 0.5 #wait 0.5 sec bw updates
    transform_timeout: 0.2 #tf data
    tf_buffer_duration: 30.0 
    stack_size_to_use: 40000000

    # Loop closure manual
    enable_interactive_mode: true 

    # Correlation params slam vs lidar to movement and loops
    use_scan_matching: true  #current and prev
    use_scan_barycenter: true 
    minimum_travel_distance: 0.3
    minimum_travel_heading: 0.5 #28
    scan_buffer_size: 10
    scan_buffer_maximum_scan_distance: 10.0
    link_match_minimum_response_fine: 0.1
    link_scan_maximum_distance: 1.5
    loop_search_maximum_distance: 3.0
    do_loop_closing: true
    loop_match_minimum_chain_size: 10 #need atleast 10 scans 
    loop_match_maximum_variance_coarse: 3.0 #allows some error
    loop_match_minimum_response_coarse: 0.35 
    loop_match_minimum_response_fine: 0.45

    # Correlation parameters (fine)
    correlation_search_space_dimension: 0.5
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.1

    # Correlation parameters (loop closure)
    loop_search_space_dimension: 8.0
    loop_search_space_resolution: 0.05
    loop_search_space_smear_deviation: 0.03

    # Scan matcher
    distance_variance_penalty: 0.5
    angle_variance_penalty: 1.0
    fine_search_angle_offset: 0.00349
    coarse_search_angle_offset: 0.349
    coarse_angle_resolution: 0.0349
    minimum_angle_penalty: 0.9
    minimum_distance_penalty: 0.5
    use_response_expansion: true
